CREATE TABLE REGIONS (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE COUNTRIES (
    COUNTRY_ID NUMBER PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(50) NOT NULL,
    REGION_ID NUMBER,
    CONSTRAINT FK_COUNTRIES_REGIONS FOREIGN KEY (REGION_ID) 
        REFERENCES REGIONS (REGION_ID) ON DELETE CASCADE
);

CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER PRIMARY KEY,
    STREET_ADDRESS VARCHAR2(100),
    POSTAL_CODE VARCHAR2(20),
    COUNTRY_ID NUMBER,
    CONSTRAINT FK_LOCATIONS_COUNTRY FOREIGN KEY (COUNTRY_ID) 
        REFERENCES COUNTRIES (COUNTRY_ID)
);

CREATE TABLE JOBS (
    JOB_ID NUMBER PRIMARY KEY,
    MIN_SALARY NUMBER NOT NULL,
    MAX_SALARY NUMBER NOT NULL,
    CHECK (MIN_SALARY < MAX_SALARY - 2000)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID NUMBER NOT NULL, 
    COMMISSION_PCT NUMBER(5,2),
    MANAGER_ID NUMBER,
    DEPARTMENT_ID NUMBER,
    CONSTRAINT FK_EMPLOYEES_JOBS FOREIGN KEY (JOB_ID) 
        REFERENCES JOBS (JOB_ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMPLOYEES_MANAGER FOREIGN KEY (MANAGER_ID) 
        REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
    MANAGER_ID NUMBER NOT NULL,
    LOCATION_ID NUMBER NOT NULL,
    CONSTRAINT FK_DEPARTMENTS_MANAGER FOREIGN KEY (MANAGER_ID) 
        REFERENCES EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT FK_DEPARTMENTS_LOCATION FOREIGN KEY (LOCATION_ID) 
        REFERENCES LOCATIONS (LOCATION_ID)
);


CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID NUMBER,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    JOB_ID NUMBER NOT NULL,
    DEPARTMENT_ID NUMBER NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID, START_DATE)
); 


ALTER TABLE LOCATIONS ADD CITY VARCHAR2(100) NOT NULL;
ALTER TABLE LOCATIONS ADD STATE_PROVINCE VARCHAR2(100);
ALTER TABLE JOBS ADD JOB_TITLE VARCHAR2(100) NOT NULL;
ALTER TABLE EMPLOYEES ADD SALARY NUMBER NOT NULL;

ALTER TABLE JOB_HISTORY 
ADD CONSTRAINT FK_JOBHISTORY_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) 
    REFERENCES EMPLOYEES (EMPLOYEE_ID) ON DELETE CASCADE;

ALTER TABLE JOB_HISTORY 
ADD CONSTRAINT FK_JOBHISTORY_JOB FOREIGN KEY (JOB_ID) 
    REFERENCES JOBS (JOB_ID) ON DELETE CASCADE;

ALTER TABLE JOB_HISTORY 
ADD CONSTRAINT FK_JOBHISTORY_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) 
    REFERENCES DEPARTMENTS (DEPARTMENT_ID) ON DELETE CASCADE;

ALTER TABLE COUNTRIES
DROP CONSTRAINT FK_COUNTRIES_REGIONS;

ALTER TABLE COUNTRIES MODIFY REGION_ID NUMBER NOT NULL;

ALTER TABLE LOCATIONS MODIFY POSTAL_CODE VARCHAR2(20) NOT NULL;
ALTER TABLE LOCATIONS MODIFY STREET_ADDRESS VARCHAR2(100) NOT NULL;
ALTER TABLE LOCATIONS MODIFY COUNTRY_ID NUMBER NOT NULL;


INSERT INTO JOBS (JOB_ID, MIN_SALARY, MAX_SALARY, JOB_TITLE) 
VALUES (1, 3000, 7000, 'Pielegniarka');

INSERT INTO JOBS (JOB_ID, MIN_SALARY, MAX_SALARY, JOB_TITLE) 
VALUES (2, 4000, 8000, 'Recepcjonistka');

INSERT INTO JOBS (JOB_ID, MIN_SALARY, MAX_SALARY, JOB_TITLE) 
VALUES (3, 5000, 10000, 'Lekarz');

INSERT INTO JOBS (JOB_ID, MIN_SALARY, MAX_SALARY, JOB_TITLE) 
VALUES (4, 3500, 7500, 'Pomocnik lekarza');



INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (1, 'Jan', 'Kowalski', 'jan@firma.pl', '123-456-789', TO_DATE('2025-03-04', 'YYYY-MM-DD'), 1, 5200, NULL, NULL, NULL);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (2, 'Anna', 'Nowak', 'anna@firma.pl', '234-567-890', TO_DATE('2025-02-10', 'YYYY-MM-DD'), 2, 4333, 0.05, 1, NULL);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (3, 'Piotr', 'Solnicki', 'piotr@firma.pl', '345-678-901', TO_DATE('2025-01-15', 'YYYY-MM-DD'), 3, 7800, 0.07, NULL, NULL);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (4, 'Maria', 'Walaszek', 'mariak@firma.pl', NULL, TO_DATE('2024-12-20', 'YYYY-MM-DD'), 4, 4500, NULL, 3, NULL);

UPDATE EMPLOYEES
SET MANAGER_ID = 1
WHERE EMPLOYEE_ID IN (2, 3);


UPDATE JOBS
SET MIN_SALARY = MIN_SALARY + 500,
    MAX_SALARY = MAX_SALARY + 500
WHERE UPPER(JOB_TITLE) LIKE '%B%' OR UPPER(JOB_TITLE) LIKE '%S%';


DELETE FROM JOBS
WHERE MAX_SALARY > 9000;

DROP TABLE JOB_HISTORY;

FLASHBACK TABLE JOB_HISTORY TO BEFORE DROP;


